/* Generated by re2c 1.3 on Thu Sep 30 08:48:51 2021 */
/**

	MultiMarkdown 6 -- Lightweight markup processor to produce HTML, LaTeX, and more.

	@file lexer.re

	@brief Description of the regular expressions used to define tokens,
	used by re2c to create a lexer/tokenizer.


	@author	Fletcher T. Penney
	@bug

**/

/*

	Copyright © 2016 - 2017 Fletcher T. Penney.


	The `MultiMarkdown 6` project is released under the MIT License..

	GLibFacade.c and GLibFacade.h are from the MultiMarkdown v4 project:

		https://github.com/fletcher/MultiMarkdown-4/

	MMD 4 is released under both the MIT License and GPL.


	CuTest is released under the zlib/libpng license. See CuTest.c for the text
	of the license.


	## The MIT License ##

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in
	all copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
	THE SOFTWARE.

*/

#include "lexer.h"
#include "libMultiMarkdown.h"
#include "parser.h"


// Basic scanner struct

#define YYCTYPE		unsigned char
#define YYCURSOR	s->cur
#define YYMARKER	s->ptr
#define YYCTXMARKER	s->ctx

int scan(Scanner * s, const char * stop) {

scan:

	if (s->cur >= stop) {
		return 0;
	}

	s->start = s->cur;


	{
		YYCTYPE yych;
		unsigned int yyaccept = 0;
		yych = *YYCURSOR;

		switch (yych) {
			case '\t':
				goto yy4;

			case '\n':
				goto yy6;

			case '\r':
				goto yy8;

			case ' ':
				goto yy9;

			case '!':
				goto yy10;

			case '"':
				goto yy11;

			case '#':
				goto yy13;

			case '$':
				goto yy15;

			case '%':
				goto yy17;

			case '&':
				goto yy19;

			case '\'':
				goto yy21;

			case '(':
				goto yy23;

			case ')':
				goto yy25;

			case '*':
				goto yy27;

			case '+':
				goto yy29;

			case '-':
				goto yy31;

			case '.':
				goto yy33;

			case '/':
				goto yy34;

			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
				goto yy36;

			case ':':
				goto yy37;

			case '<':
				goto yy39;

			case '=':
				goto yy41;

			case '>':
				goto yy43;

			case '[':
				goto yy45;

			case '\\':
				goto yy47;

			case ']':
				goto yy49;

			case '^':
				goto yy51;

			case '_':
				goto yy53;

			case '`':
				goto yy55;

			case '{':
				goto yy58;

			case '|':
				goto yy60;

			case '}':
				goto yy63;

			case '~':
				goto yy65;

			case 0xC2:
				goto yy67;

			case 0xEF:
				goto yy68;

			default:
				goto yy2;
		}

yy2:
		++YYCURSOR;
yy3: {
			goto scan;
		}
yy4:
		++YYCURSOR;
		{
			return INDENT_TAB;
		}
yy6:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case ' ':
				goto yy69;

			default:
				goto yy7;
		}

yy7: {
			return TEXT_NL;
		}
yy8:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '\n':
				goto yy6;

			case ' ':
				goto yy69;

			default:
				goto yy7;
		}

yy9:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '\t':
				goto yy71;

			case '\n':
				goto yy73;

			case '\r':
				goto yy74;

			case ' ':
				goto yy75;

			case 0xC2:
				goto yy77;

			default:
				goto yy3;
		}

yy10:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '[':
				goto yy78;

			default:
				goto yy3;
		}

yy11:
		++YYCURSOR;
		{
			return QUOTE_DOUBLE;
		}
yy13:
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 0x00:
			case '\n':
				YYCTXMARKER = YYCURSOR;
				goto yy79;

			case '\t':
			case ' ':
				YYCTXMARKER = YYCURSOR;
				goto yy81;

			case '\r':
				YYCTXMARKER = YYCURSOR;
				goto yy84;

			case '#':
				goto yy85;

			case 0xC2:
				YYCTXMARKER = YYCURSOR;
				goto yy86;

			default:
				goto yy14;
		}

yy14: {
			return TEXT_HASH;
		}
yy15:
		yych = *++YYCURSOR;

		switch (yych) {
			case '$':
				goto yy87;

			default:
				goto yy16;
		}

yy16: {
			return MATH_DOLLAR_SINGLE;
		}
yy17:
		++YYCURSOR;
		{
			return TEXT_PERCENT;
		}
yy19:
		yyaccept = 3;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '#':
				goto yy89;

			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':
				goto yy90;

			case 'A':
			case 'a':
				goto yy92;

			default:
				goto yy20;
		}

yy20: {
			return AMPERSAND;
		}
yy21:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\'':
				goto yy93;

			default:
				goto yy22;
		}

yy22: {
			return QUOTE_SINGLE;
		}
yy23:
		++YYCURSOR;
		{
			return PAREN_LEFT;
		}
yy25:
		++YYCURSOR;
		{
			return PAREN_RIGHT;
		}
yy27:
		++YYCURSOR;
		{
			return STAR;
		}
yy29:
		yyaccept = 4;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '+':
				goto yy95;

			default:
				goto yy30;
		}

yy30: {
			return PLUS;
		}
yy31:
		yych = *++YYCURSOR;

		switch (yych) {
			case '-':
				goto yy96;

			default:
				goto yy32;
		}

yy32: {
			return DASH_N;
		}
yy33:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case ' ':
				goto yy98;

			case '.':
				goto yy99;

			default:
				goto yy3;
		}

yy34:
		++YYCURSOR;
		{
			return SLASH;
		}
yy36:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '.':
				goto yy100;

			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
				goto yy101;

			default:
				goto yy3;
		}

yy37:
		++YYCURSOR;
		{
			return COLON;
		}
yy39:
		yyaccept = 5;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '!':
				goto yy103;

			case '<':
				goto yy104;

			default:
				goto yy40;
		}

yy40: {
			return ANGLE_LEFT;
		}
yy41:
		yyaccept = 6;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '=':
				goto yy105;

			default:
				goto yy42;
		}

yy42: {
			return EQUAL;
		}
yy43:
		++YYCURSOR;
		{
			return ANGLE_RIGHT;
		}
yy45:
		yych = *++YYCURSOR;

		switch (yych) {
			case '#':
				goto yy106;

			case '%':
				goto yy108;

			case '>':
				goto yy110;

			case '?':
				goto yy112;

			case '[':
				goto yy114;

			case '^':
				goto yy116;

			default:
				goto yy46;
		}

yy46: {
			return BRACKET_LEFT;
		}
yy47:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy118;

			case '\r':
				goto yy120;

			case ' ':
				goto yy121;

			case '!':
				goto yy123;

			case '"':
				goto yy125;

			case '#':
				goto yy127;

			case '$':
				goto yy129;

			case '%':
				goto yy131;

			case '&':
				goto yy133;

			case '\'':
				goto yy135;

			case '(':
				goto yy137;

			case ')':
				goto yy139;

			case '*':
				goto yy141;

			case '+':
				goto yy143;

			case ',':
				goto yy145;

			case '-':
				goto yy147;

			case '.':
				goto yy149;

			case '/':
				goto yy151;

			case ':':
				goto yy153;

			case ';':
				goto yy155;

			case '<':
				goto yy157;

			case '=':
				goto yy159;

			case '>':
				goto yy161;

			case '?':
				goto yy163;

			case '@':
				goto yy165;

			case '[':
				goto yy167;

			case '\\':
				goto yy169;

			case ']':
				goto yy171;

			case '^':
				goto yy173;

			case '_':
				goto yy175;

			case '`':
				goto yy177;

			case '{':
				goto yy179;

			case '|':
				goto yy181;

			case '}':
				goto yy183;

			case '~':
				goto yy185;

			default:
				goto yy48;
		}

yy48: {
			return TEXT_BACKSLASH;
		}
yy49:
		yych = *++YYCURSOR;

		switch (yych) {
			case ']':
				goto yy187;

			default:
				goto yy50;
		}

yy50: {
			return BRACKET_RIGHT;
		}
yy51:
		++YYCURSOR;
		{
			return SUPERSCRIPT;
		}
yy53:
		++YYCURSOR;
		{
			return UL;
		}
yy55:
		yych = *++YYCURSOR;

		switch (yych) {
			case '`':
				goto yy55;

			default:
				goto yy57;
		}

yy57: {
			return BACKTICK;
		}
yy58:
		yyaccept = 7;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '+':
				goto yy189;

			case '-':
				goto yy190;

			case '=':
				goto yy191;

			case '>':
				goto yy193;

			case '{':
				goto yy194;

			case '~':
				goto yy196;

			default:
				goto yy59;
		}

yy59: {
			return TEXT_BRACE_LEFT;
		}
yy60:
		yych = *++YYCURSOR;

		switch (yych) {
			case '|':
				goto yy60;

			default:
				goto yy62;
		}

yy62: {
			return PIPE;
		}
yy63:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy197;

			default:
				goto yy64;
		}

yy64: {
			return TEXT_BRACE_RIGHT;
		}
yy65:
		yyaccept = 8;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '>':
				goto yy199;

			case '~':
				goto yy201;

			default:
				goto yy66;
		}

yy66: {
			return SUBSCRIPT;
		}
yy67:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 0xA0:
				goto yy202;

			default:
				goto yy3;
		}

yy68:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 0xBF:
				goto yy203;

			default:
				goto yy3;
		}

yy69:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x00:
			case 0x01:
			case 0x02:
			case 0x03:
			case 0x04:
			case 0x05:
			case 0x06:
			case 0x07:
			case 0x08:
			case '\v':
			case '\f':
			case 0x0E:
			case 0x0F:
			case 0x10:
			case 0x11:
			case 0x12:
			case 0x13:
			case 0x14:
			case 0x15:
			case 0x16:
			case 0x17:
			case 0x18:
			case 0x19:
			case 0x1A:
			case 0x1B:
			case 0x1C:
			case 0x1D:
			case 0x1E:
			case 0x1F:
			case '!':
			case '"':
			case '#':
			case '$':
			case '%':
			case '&':
			case '\'':
			case '(':
			case ')':
			case '*':
			case '+':
			case ',':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case ':':
			case ';':
			case '<':
			case '=':
			case '>':
			case '?':
			case '@':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '[':
			case '\\':
			case ']':
			case '^':
			case '_':
			case '`':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':
			case '{':
			case '|':
			case '}':
			case '~':
			case 0x7F:
				YYCTXMARKER = YYCURSOR;
				goto yy204;

			case 0xC2:
			case 0xC3:
			case 0xC4:
			case 0xC5:
			case 0xC6:
			case 0xC7:
			case 0xC8:
			case 0xC9:
			case 0xCA:
			case 0xCB:
			case 0xCC:
			case 0xCD:
			case 0xCE:
			case 0xCF:
			case 0xD0:
			case 0xD1:
			case 0xD2:
			case 0xD3:
			case 0xD4:
			case 0xD5:
			case 0xD6:
			case 0xD7:
			case 0xD8:
			case 0xD9:
			case 0xDA:
			case 0xDB:
			case 0xDC:
			case 0xDD:
			case 0xDE:
			case 0xDF:
				YYCTXMARKER = YYCURSOR;
				goto yy206;

			case 0xE0:
				YYCTXMARKER = YYCURSOR;
				goto yy207;

			case 0xE1:
			case 0xE2:
			case 0xE3:
			case 0xE4:
			case 0xE5:
			case 0xE6:
			case 0xE7:
			case 0xE8:
			case 0xE9:
			case 0xEA:
			case 0xEB:
			case 0xEC:
			case 0xED:
			case 0xEE:
			case 0xEF:
				YYCTXMARKER = YYCURSOR;
				goto yy208;

			case 0xF0:
				YYCTXMARKER = YYCURSOR;
				goto yy209;

			case 0xF1:
			case 0xF2:
			case 0xF3:
				YYCTXMARKER = YYCURSOR;
				goto yy210;

			case 0xF4:
				YYCTXMARKER = YYCURSOR;
				goto yy211;

			default:
				goto yy70;
		}

yy70:
		YYCURSOR = YYMARKER;

		switch (yyaccept) {
			case 0:
				goto yy7;

			case 1:
				goto yy3;

			case 2:
				goto yy14;

			case 3:
				goto yy20;

			case 4:
				goto yy30;

			case 5:
				goto yy40;

			case 6:
				goto yy42;

			case 7:
				goto yy59;

			case 8:
				goto yy66;

			case 9:
				goto yy76;

			case 10:
				goto yy83;

			case 11:
				goto yy195;

			case 12:
				goto yy213;

			case 13:
				goto yy229;

			case 14:
				goto yy252;

			case 15:
				goto yy286;

			case 16:
				goto yy292;

			case 17:
				goto yy320;

			case 18:
				goto yy335;

			default:
				goto yy345;
		}

yy71:
		++YYCURSOR;
		YYCURSOR -= 1;
		{
			return NON_INDENT_SPACE;
		}
yy73:
		++YYCURSOR;
		goto yy7;
yy74:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy73;

			default:
				goto yy7;
		}

yy75:
		yyaccept = 9;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '\n':
				goto yy212;

			case '\r':
				goto yy214;

			case ' ':
				goto yy215;

			case 0xC2:
				goto yy216;

			default:
				goto yy76;
		}

yy76: {
			return NON_INDENT_SPACE;
		}
yy77:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy75;

			default:
				goto yy70;
		}

yy78:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x00:
			case 0x01:
			case 0x02:
			case 0x03:
			case 0x04:
			case 0x05:
			case 0x06:
			case 0x07:
			case 0x08:
			case '\t':
			case '\n':
			case '\v':
			case '\f':
			case '\r':
			case 0x0E:
			case 0x0F:
			case 0x10:
			case 0x11:
			case 0x12:
			case 0x13:
			case 0x14:
			case 0x15:
			case 0x16:
			case 0x17:
			case 0x18:
			case 0x19:
			case 0x1A:
			case 0x1B:
			case 0x1C:
			case 0x1D:
			case 0x1E:
			case 0x1F:
			case ' ':
			case '!':
			case '"':
			case '#':
			case '$':
			case '%':
			case '&':
			case '\'':
			case '(':
			case ')':
			case '*':
			case '+':
			case ',':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case ':':
			case ';':
			case '<':
			case '=':
			case '>':
			case '?':
			case '@':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case ']':
			case '^':
			case '_':
			case '`':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':
			case '{':
			case '|':
			case '}':
			case '~':
			case 0x7F:
				YYCTXMARKER = YYCURSOR;
				goto yy217;

			case 0xC2:
			case 0xC3:
			case 0xC4:
			case 0xC5:
			case 0xC6:
			case 0xC7:
			case 0xC8:
			case 0xC9:
			case 0xCA:
			case 0xCB:
			case 0xCC:
			case 0xCD:
			case 0xCE:
			case 0xCF:
			case 0xD0:
			case 0xD1:
			case 0xD2:
			case 0xD3:
			case 0xD4:
			case 0xD5:
			case 0xD6:
			case 0xD7:
			case 0xD8:
			case 0xD9:
			case 0xDA:
			case 0xDB:
			case 0xDC:
			case 0xDD:
			case 0xDE:
			case 0xDF:
				YYCTXMARKER = YYCURSOR;
				goto yy219;

			case 0xE0:
				YYCTXMARKER = YYCURSOR;
				goto yy220;

			case 0xE1:
			case 0xE2:
			case 0xE3:
			case 0xE4:
			case 0xE5:
			case 0xE6:
			case 0xE7:
			case 0xE8:
			case 0xE9:
			case 0xEA:
			case 0xEB:
			case 0xEC:
			case 0xED:
			case 0xEE:
			case 0xEF:
				YYCTXMARKER = YYCURSOR;
				goto yy221;

			case 0xF0:
				YYCTXMARKER = YYCURSOR;
				goto yy222;

			case 0xF1:
			case 0xF2:
			case 0xF3:
				YYCTXMARKER = YYCURSOR;
				goto yy223;

			case 0xF4:
				YYCTXMARKER = YYCURSOR;
				goto yy224;

			default:
				goto yy70;
		}

yy79:
		++YYCURSOR;
yy80:
		YYCURSOR = YYCTXMARKER;
		{
			return HASH1;
		}
yy81:
		yyaccept = 10;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 0x00:
			case '\n':
				goto yy79;

			case '\t':
			case ' ':
				goto yy81;

			case '\r':
				goto yy84;

			case 0xC2:
				goto yy86;

			default:
				goto yy83;
		}

yy83: {
			return HASH1;
		}
yy84:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy79;

			default:
				goto yy80;
		}

yy85:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x00:
			case '\n':
				YYCTXMARKER = YYCURSOR;
				goto yy225;

			case '\t':
			case ' ':
				YYCTXMARKER = YYCURSOR;
				goto yy227;

			case '\r':
				YYCTXMARKER = YYCURSOR;
				goto yy230;

			case '#':
				goto yy231;

			case 0xC2:
				YYCTXMARKER = YYCURSOR;
				goto yy232;

			default:
				goto yy70;
		}

yy86:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy81;

			default:
				goto yy70;
		}

yy87:
		++YYCURSOR;
		{
			return MATH_DOLLAR_DOUBLE;
		}
yy89:
		yych = *++YYCURSOR;

		switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
				goto yy233;

			case 'X':
			case 'x':
				goto yy235;

			default:
				goto yy70;
		}

yy90:
		yych = *++YYCURSOR;
yy91:

		switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':
				goto yy90;

			case ';':
				goto yy236;

			default:
				goto yy70;
		}

yy92:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'M':
			case 'm':
				goto yy238;

			default:
				goto yy91;
		}

yy93:
		++YYCURSOR;
		{
			return QUOTE_RIGHT_ALT;
		}
yy95:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy239;

			default:
				goto yy70;
		}

yy96:
		yych = *++YYCURSOR;

		switch (yych) {
			case '-':
				goto yy241;

			case '>':
				goto yy243;

			case '}':
				goto yy245;

			default:
				goto yy97;
		}

yy97: {
			return DASH_N;
		}
yy98:
		yych = *++YYCURSOR;

		switch (yych) {
			case '.':
				goto yy247;

			default:
				goto yy70;
		}

yy99:
		yych = *++YYCURSOR;

		switch (yych) {
			case '.':
				goto yy248;

			default:
				goto yy70;
		}

yy100:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\t':
			case ' ':
				YYCTXMARKER = YYCURSOR;
				goto yy250;

			case '\n':
				YYCTXMARKER = YYCURSOR;
				goto yy253;

			case '\r':
				YYCTXMARKER = YYCURSOR;
				goto yy254;

			case 0xC2:
				YYCTXMARKER = YYCURSOR;
				goto yy255;

			default:
				goto yy70;
		}

yy101:
		yych = *++YYCURSOR;

		switch (yych) {
			case '.':
				goto yy100;

			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
				goto yy101;

			default:
				goto yy70;
		}

yy103:
		yych = *++YYCURSOR;

		switch (yych) {
			case '-':
				goto yy256;

			default:
				goto yy70;
		}

yy104:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy257;

			default:
				goto yy70;
		}

yy105:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy259;

			default:
				goto yy70;
		}

yy106:
		++YYCURSOR;
		{
			return BRACKET_CITATION_LEFT;
		}
yy108:
		++YYCURSOR;
		{
			return BRACKET_VARIABLE_LEFT;
		}
yy110:
		++YYCURSOR;
		{
			return BRACKET_ABBREVIATION_LEFT;
		}
yy112:
		++YYCURSOR;
		{
			return BRACKET_GLOSSARY_LEFT;
		}
yy114:
		++YYCURSOR;
		{
			return BRACKET_DOUBLE_LEFT;
		}
yy116:
		++YYCURSOR;
		{
			return BRACKET_FOOTNOTE_LEFT;
		}
yy118:
		++YYCURSOR;
yy119: {
			return TEXT_LINEBREAK;
		}
yy120:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy118;

			default:
				goto yy119;
		}

yy121:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy123:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy125:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy127:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy129:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy131:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy133:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy135:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy137:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy139:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy141:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy143:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy145:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy147:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy149:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy151:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy153:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy155:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy157:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy159:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy161:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy163:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy165:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy167:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy169:
		yych = *++YYCURSOR;

		switch (yych) {
			case '(':
				goto yy261;

			case ')':
				goto yy263;

			case '[':
				goto yy265;

			case ']':
				goto yy267;

			default:
				goto yy170;
		}

yy170: {
			return ESCAPED_CHARACTER;
		}
yy171:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy173:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy175:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy177:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy179:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy181:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy183:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy185:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy187:
		++YYCURSOR;
		{
			return BRACKET_DOUBLE_RIGHT;
		}
yy189:
		yych = *++YYCURSOR;

		switch (yych) {
			case '+':
				goto yy269;

			default:
				goto yy70;
		}

yy190:
		yych = *++YYCURSOR;

		switch (yych) {
			case '-':
				goto yy271;

			default:
				goto yy70;
		}

yy191:
		yych = *++YYCURSOR;

		switch (yych) {
			case '=':
				goto yy273;

			default:
				goto yy192;
		}

yy192: {
			return RAW_FILTER_LEFT;
		}
yy193:
		yych = *++YYCURSOR;

		switch (yych) {
			case '>':
				goto yy275;

			default:
				goto yy70;
		}

yy194:
		yyaccept = 11;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 'T':
				goto yy277;

			default:
				goto yy195;
		}

yy195: {
			return BRACE_DOUBLE_LEFT;
		}
yy196:
		yych = *++YYCURSOR;

		switch (yych) {
			case '~':
				goto yy278;

			default:
				goto yy70;
		}

yy197:
		++YYCURSOR;
		{
			return BRACE_DOUBLE_RIGHT;
		}
yy199:
		++YYCURSOR;
		{
			return CRITIC_SUB_DIV;
		}
yy201:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy280;

			default:
				goto yy70;
		}

yy202:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\t':
				goto yy71;

			case ' ':
				goto yy75;

			case 0xC2:
				goto yy77;

			default:
				goto yy70;
		}

yy203:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xBC:
				goto yy282;

			default:
				goto yy70;
		}

yy204:
		++YYCURSOR;
		YYCURSOR = YYCTXMARKER;
		{
			return TEXT_NL_SP;
		}
yy206:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy204;

			default:
				goto yy70;
		}

yy207:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy206;

			default:
				goto yy70;
		}

yy208:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy206;

			default:
				goto yy70;
		}

yy209:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy208;

			default:
				goto yy70;
		}

yy210:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy208;

			default:
				goto yy70;
		}

yy211:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
				goto yy208;

			default:
				goto yy70;
		}

yy212:
		yyaccept = 12;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case ' ':
				goto yy284;

			default:
				goto yy213;
		}

yy213: {
			return TEXT_LINEBREAK;
		}
yy214:
		yyaccept = 12;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '\n':
				goto yy212;

			case ' ':
				goto yy284;

			default:
				goto yy213;
		}

yy215:
		yyaccept = 9;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '\n':
				goto yy212;

			case '\r':
				goto yy214;

			case ' ':
				goto yy285;

			case 0xC2:
				goto yy287;

			default:
				goto yy76;
		}

yy216:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy215;

			default:
				goto yy70;
		}

yy217:
		++YYCURSOR;
		YYCURSOR = YYCTXMARKER;
		{
			return BRACKET_IMAGE_LEFT;
		}
yy219:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy217;

			default:
				goto yy70;
		}

yy220:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy219;

			default:
				goto yy70;
		}

yy221:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy219;

			default:
				goto yy70;
		}

yy222:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy221;

			default:
				goto yy70;
		}

yy223:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy221;

			default:
				goto yy70;
		}

yy224:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
				goto yy221;

			default:
				goto yy70;
		}

yy225:
		++YYCURSOR;
yy226:
		YYCURSOR = YYCTXMARKER;
		{
			return HASH2;
		}
yy227:
		yyaccept = 13;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 0x00:
			case '\n':
				goto yy225;

			case '\t':
			case ' ':
				goto yy227;

			case '\r':
				goto yy230;

			case 0xC2:
				goto yy232;

			default:
				goto yy229;
		}

yy229: {
			return HASH2;
		}
yy230:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy225;

			default:
				goto yy226;
		}

yy231:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x00:
			case '\n':
				YYCTXMARKER = YYCURSOR;
				goto yy288;

			case '\t':
			case ' ':
				YYCTXMARKER = YYCURSOR;
				goto yy290;

			case '\r':
				YYCTXMARKER = YYCURSOR;
				goto yy293;

			case '#':
				goto yy294;

			case 0xC2:
				YYCTXMARKER = YYCURSOR;
				goto yy295;

			default:
				goto yy70;
		}

yy232:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy227;

			default:
				goto yy70;
		}

yy233:
		yych = *++YYCURSOR;

		switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
				goto yy233;

			case ';':
				goto yy296;

			default:
				goto yy70;
		}

yy235:
		yych = *++YYCURSOR;

		switch (yych) {
			case ';':
				goto yy70;

			default:
				goto yy299;
		}

yy236:
		++YYCURSOR;
		{
			return HTML_ENTITY;
		}
yy238:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'P':
			case 'p':
				goto yy300;

			default:
				goto yy91;
		}

yy239:
		++YYCURSOR;
		{
			return CRITIC_ADD_CLOSE;
		}
yy241:
		++YYCURSOR;
		{
			return DASH_M;
		}
yy243:
		++YYCURSOR;
		{
			return HTML_COMMENT_STOP;
		}
yy245:
		++YYCURSOR;
		{
			return CRITIC_DEL_CLOSE;
		}
yy247:
		yych = *++YYCURSOR;

		switch (yych) {
			case ' ':
				goto yy301;

			default:
				goto yy70;
		}

yy248:
		++YYCURSOR;
		{
			return ELLIPSIS;
		}
yy250:
		yyaccept = 14;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '\t':
			case ' ':
				goto yy250;

			case 0xC2:
				goto yy255;

			default:
				goto yy252;
		}

yy252:
		YYCURSOR = YYCTXMARKER;
		{
			return TEXT_NUMBER_POSS_LIST;
		}
yy253:
		++YYCURSOR;
		goto yy252;
yy254:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy253;

			default:
				goto yy252;
		}

yy255:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy250;

			default:
				goto yy70;
		}

yy256:
		yych = *++YYCURSOR;

		switch (yych) {
			case '-':
				goto yy302;

			default:
				goto yy70;
		}

yy257:
		++YYCURSOR;
		{
			return CRITIC_COM_CLOSE;
		}
yy259:
		++YYCURSOR;
		{
			return CRITIC_HI_CLOSE;
		}
yy261:
		++YYCURSOR;
		{
			return MATH_PAREN_OPEN;
		}
yy263:
		++YYCURSOR;
		{
			return MATH_PAREN_CLOSE;
		}
yy265:
		++YYCURSOR;
		{
			return MATH_BRACKET_OPEN;
		}
yy267:
		++YYCURSOR;
		{
			return MATH_BRACKET_CLOSE;
		}
yy269:
		++YYCURSOR;
		{
			return CRITIC_ADD_OPEN;
		}
yy271:
		++YYCURSOR;
		{
			return CRITIC_DEL_OPEN;
		}
yy273:
		++YYCURSOR;
		{
			return CRITIC_HI_OPEN;
		}
yy275:
		++YYCURSOR;
		{
			return CRITIC_COM_OPEN;
		}
yy277:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'O':
				goto yy304;

			default:
				goto yy70;
		}

yy278:
		++YYCURSOR;
		{
			return CRITIC_SUB_OPEN;
		}
yy280:
		++YYCURSOR;
		{
			return CRITIC_SUB_CLOSE;
		}
yy282:
		++YYCURSOR;
		{
			return OBJECT_REPLACEMENT_CHARACTER;
		}
yy284:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x00:
			case 0x01:
			case 0x02:
			case 0x03:
			case 0x04:
			case 0x05:
			case 0x06:
			case 0x07:
			case 0x08:
			case '\v':
			case '\f':
			case 0x0E:
			case 0x0F:
			case 0x10:
			case 0x11:
			case 0x12:
			case 0x13:
			case 0x14:
			case 0x15:
			case 0x16:
			case 0x17:
			case 0x18:
			case 0x19:
			case 0x1A:
			case 0x1B:
			case 0x1C:
			case 0x1D:
			case 0x1E:
			case 0x1F:
			case '!':
			case '"':
			case '#':
			case '$':
			case '%':
			case '&':
			case '\'':
			case '(':
			case ')':
			case '*':
			case '+':
			case ',':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case ':':
			case ';':
			case '<':
			case '=':
			case '>':
			case '?':
			case '@':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '[':
			case '\\':
			case ']':
			case '^':
			case '_':
			case '`':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':
			case '{':
			case '|':
			case '}':
			case '~':
			case 0x7F:
				YYCTXMARKER = YYCURSOR;
				goto yy305;

			case 0xC2:
			case 0xC3:
			case 0xC4:
			case 0xC5:
			case 0xC6:
			case 0xC7:
			case 0xC8:
			case 0xC9:
			case 0xCA:
			case 0xCB:
			case 0xCC:
			case 0xCD:
			case 0xCE:
			case 0xCF:
			case 0xD0:
			case 0xD1:
			case 0xD2:
			case 0xD3:
			case 0xD4:
			case 0xD5:
			case 0xD6:
			case 0xD7:
			case 0xD8:
			case 0xD9:
			case 0xDA:
			case 0xDB:
			case 0xDC:
			case 0xDD:
			case 0xDE:
			case 0xDF:
				YYCTXMARKER = YYCURSOR;
				goto yy307;

			case 0xE0:
				YYCTXMARKER = YYCURSOR;
				goto yy308;

			case 0xE1:
			case 0xE2:
			case 0xE3:
			case 0xE4:
			case 0xE5:
			case 0xE6:
			case 0xE7:
			case 0xE8:
			case 0xE9:
			case 0xEA:
			case 0xEB:
			case 0xEC:
			case 0xED:
			case 0xEE:
			case 0xEF:
				YYCTXMARKER = YYCURSOR;
				goto yy309;

			case 0xF0:
				YYCTXMARKER = YYCURSOR;
				goto yy310;

			case 0xF1:
			case 0xF2:
			case 0xF3:
				YYCTXMARKER = YYCURSOR;
				goto yy311;

			case 0xF4:
				YYCTXMARKER = YYCURSOR;
				goto yy312;

			default:
				goto yy70;
		}

yy285:
		yyaccept = 15;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '\n':
				goto yy212;

			case '\r':
				goto yy214;

			case ' ':
				goto yy313;

			case 0xC2:
				goto yy315;

			default:
				goto yy286;
		}

yy286: {
			return INDENT_SPACE;
		}
yy287:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy285;

			default:
				goto yy70;
		}

yy288:
		++YYCURSOR;
yy289:
		YYCURSOR = YYCTXMARKER;
		{
			return HASH3;
		}
yy290:
		yyaccept = 16;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 0x00:
			case '\n':
				goto yy288;

			case '\t':
			case ' ':
				goto yy290;

			case '\r':
				goto yy293;

			case 0xC2:
				goto yy295;

			default:
				goto yy292;
		}

yy292: {
			return HASH3;
		}
yy293:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy288;

			default:
				goto yy289;
		}

yy294:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x00:
			case '\n':
				YYCTXMARKER = YYCURSOR;
				goto yy316;

			case '\t':
			case ' ':
				YYCTXMARKER = YYCURSOR;
				goto yy318;

			case '\r':
				YYCTXMARKER = YYCURSOR;
				goto yy321;

			case '#':
				goto yy322;

			case 0xC2:
				YYCTXMARKER = YYCURSOR;
				goto yy323;

			default:
				goto yy70;
		}

yy295:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy290;

			default:
				goto yy70;
		}

yy296:
		++YYCURSOR;
		{
			return HTML_ENTITY;
		}
yy298:
		yych = *++YYCURSOR;
yy299:

		switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '[':
			case '\\':
			case ']':
			case '^':
			case '_':
			case '`':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
				goto yy298;

			case ';':
				goto yy324;

			default:
				goto yy70;
		}

yy300:
		yych = *++YYCURSOR;

		switch (yych) {
			case ';':
				goto yy326;

			default:
				goto yy91;
		}

yy301:
		yych = *++YYCURSOR;

		switch (yych) {
			case '.':
				goto yy328;

			default:
				goto yy70;
		}

yy302:
		++YYCURSOR;
		{
			return HTML_COMMENT_START;
		}
yy304:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'C':
				goto yy330;

			default:
				goto yy70;
		}

yy305:
		++YYCURSOR;
		YYCURSOR = YYCTXMARKER;
		{
			return TEXT_LINEBREAK_SP;
		}
yy307:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy305;

			default:
				goto yy70;
		}

yy308:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy307;

			default:
				goto yy70;
		}

yy309:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy307;

			default:
				goto yy70;
		}

yy310:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy309;

			default:
				goto yy70;
		}

yy311:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy309;

			default:
				goto yy70;
		}

yy312:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
				goto yy309;

			default:
				goto yy70;
		}

yy313:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy212;

			case '\r':
				goto yy214;

			case ' ':
				goto yy313;

			case 0xC2:
				goto yy315;

			default:
				goto yy70;
		}

yy315:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy313;

			default:
				goto yy70;
		}

yy316:
		++YYCURSOR;
yy317:
		YYCURSOR = YYCTXMARKER;
		{
			return HASH4;
		}
yy318:
		yyaccept = 17;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 0x00:
			case '\n':
				goto yy316;

			case '\t':
			case ' ':
				goto yy318;

			case '\r':
				goto yy321;

			case 0xC2:
				goto yy323;

			default:
				goto yy320;
		}

yy320: {
			return HASH4;
		}
yy321:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy316;

			default:
				goto yy317;
		}

yy322:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x00:
			case '\n':
				YYCTXMARKER = YYCURSOR;
				goto yy331;

			case '\t':
			case ' ':
				YYCTXMARKER = YYCURSOR;
				goto yy333;

			case '\r':
				YYCTXMARKER = YYCURSOR;
				goto yy336;

			case '#':
				goto yy337;

			case 0xC2:
				YYCTXMARKER = YYCURSOR;
				goto yy338;

			default:
				goto yy70;
		}

yy323:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy318;

			default:
				goto yy70;
		}

yy324:
		++YYCURSOR;
		{
			return HTML_ENTITY;
		}
yy326:
		++YYCURSOR;
		{
			return AMPERSAND_LONG;
		}
yy328:
		++YYCURSOR;
		{
			return ELLIPSIS;
		}
yy330:
		yych = *++YYCURSOR;

		switch (yych) {
			case ':':
				goto yy339;

			case '}':
				goto yy340;

			default:
				goto yy70;
		}

yy331:
		++YYCURSOR;
yy332:
		YYCURSOR = YYCTXMARKER;
		{
			return HASH5;
		}
yy333:
		yyaccept = 18;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 0x00:
			case '\n':
				goto yy331;

			case '\t':
			case ' ':
				goto yy333;

			case '\r':
				goto yy336;

			case 0xC2:
				goto yy338;

			default:
				goto yy335;
		}

yy335: {
			return HASH5;
		}
yy336:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy331;

			default:
				goto yy332;
		}

yy337:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x00:
			case '\n':
				YYCTXMARKER = YYCURSOR;
				goto yy341;

			case '\t':
			case ' ':
				YYCTXMARKER = YYCURSOR;
				goto yy343;

			case '\r':
				YYCTXMARKER = YYCURSOR;
				goto yy346;

			case 0xC2:
				YYCTXMARKER = YYCURSOR;
				goto yy347;

			default:
				goto yy70;
		}

yy338:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy333;

			default:
				goto yy70;
		}

yy339:
		yych = *++YYCURSOR;

		switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
				goto yy348;

			default:
				goto yy70;
		}

yy340:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy349;

			default:
				goto yy70;
		}

yy341:
		++YYCURSOR;
yy342:
		YYCURSOR = YYCTXMARKER;
		{
			return HASH6;
		}
yy343:
		yyaccept = 19;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 0x00:
			case '\n':
				goto yy341;

			case '\t':
			case ' ':
				goto yy343;

			case '\r':
				goto yy346;

			case 0xC2:
				goto yy347;

			default:
				goto yy345;
		}

yy345: {
			return HASH6;
		}
yy346:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy341;

			default:
				goto yy342;
		}

yy347:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy343;

			default:
				goto yy70;
		}

yy348:
		yych = *++YYCURSOR;

		switch (yych) {
			case '-':
				goto yy351;

			case '}':
				goto yy352;

			default:
				goto yy70;
		}

yy349:
		++YYCURSOR;
		{
			return TOC;
		}
yy351:
		yych = *++YYCURSOR;

		switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
				goto yy353;

			default:
				goto yy70;
		}

yy352:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy354;

			default:
				goto yy70;
		}

yy353:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy356;

			default:
				goto yy70;
		}

yy354:
		++YYCURSOR;
		{
			return TOC_SINGLE;
		}
yy356:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy357;

			default:
				goto yy70;
		}

yy357:
		++YYCURSOR;
		{
			return TOC_RANGE;
		}
	}

}
